apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # root (encodé en base64)
  mysql-root-password: cm9vdA==
  # root (encodé en base64)
  mysql-password: cm9vdA==
  # studentdb (encodé en base64)
  mysql-database: c3R1ZGVudGRi